const IMAGES = {
    profile1: require('./profile1.svg').default,
    profile2: require('./profile2.svg').default,
    profile3: require('./profile3.svg').default,
    profile4: require('./profile4.svg').default,
    profile5: require('./profile5.svg').default,
    profile6: require('./profile6.svg').default,
    profile7: require('./profile17.svg').default,
    profile8: require('./profile18.svg').default,
    profile9: require('./profile19.svg').default,
    profile10: require('./profile20.svg').default,
    profile11: require('./profile21.svg').default,
    profile12: require('./profile22.svg').default,
    profile13: require('./profile23.svg').default,
    profile14: require('./profile24.svg').default,
    profile15: require('./profile25.svg').default,
    profile16: require('./profile26.svg').default,
    profile17: require('./profile27.svg').default,
    profile18: require('./profile28.svg').default,
    profile19: require('./profile29.svg').default,
    profile20: require('./profile30.svg').default,
    profile21: require('./profile31.svg').default,
    profile22: require('./profile65.svg').default,
}

export default IMAGES;